### ISSUE TITLE
Waarom is een menu-button een div?

### ISSUE THREAD

**Issue by KrijnHoetmer** [CathelijneVisser/redesign-funda-object-detail-page#1]
En niet een... `<button>`? :)

https://github.com/CathelijneVisser/the-startup-responsive-interactieve-website/blob/61fd43ffe0919fa949f036deedb66dae18154f10/index.html#L10

**Comment by CathelijneVisser** [comment]
Omdat ik niet door had dat je in een button een icon en tekst kon doen. Ik heb het aangepast.
