### ISSUE TITLE
Spatie in je class

### ISSUE THREAD

**Issue by RayanSp** [CathelijneVisser/redesign-funda-object-detail-page#17]
Je hebt hier een spatie in je class name, zet daar een streepje neer zoals bij de rest. Denk dat je het vergeten bent. 

https://github.com/CathelijneVisser/the-startup-responsive-interactieve-website/blob/9d49c0df38a97f4ccee99db2fb72471e4246e7eb/index.html#L87

**Comment by KrijnHoetmer** [comment]
Dit mag gewoon, zie ook de documentatie op https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class
